"""your message here

Revision ID: b8c38ea9e3d1
Revises: df4531e4266b
Create Date: 2025-05-08 11:14:25.125261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8c38ea9e3d1'
down_revision: Union[str, None] = 'df4531e4266b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_rooms', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('game_rooms', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'telegram_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('game_rooms', 'updated_at')
    op.drop_column('game_rooms', 'created_at')
    # ### end Alembic commands ###
